-- CreateTable
CREATE TABLE "public"."employee_drafts" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT,
    "name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "department" TEXT,
    "designation" TEXT,
    "company" TEXT,
    "location" TEXT,
    "grade" TEXT,
    "status" "public"."EmployeeStatus" NOT NULL DEFAULT 'active',
    "joiningDate" TEXT,
    "dateOfBirth" TEXT,
    "basicSalary" DECIMAL(12,2),
    "hra" DECIMAL(12,2),
    "allowances" DECIMAL(12,2),
    "pan" TEXT,
    "aadhaar" TEXT,
    "uan" TEXT,
    "esicNumber" TEXT,
    "pfOptIn" BOOLEAN NOT NULL DEFAULT true,
    "esiApplicable" BOOLEAN NOT NULL DEFAULT true,
    "lwfState" TEXT,
    "bankAccount" TEXT,
    "ifsc" TEXT,
    "branch" TEXT,
    "profilePic" TEXT,
    "createdBy" TEXT,
    "lastModified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "employee_drafts_pkey" PRIMARY KEY ("id")
);
